### ISSUE TITLE
老哥你是放挖矿脚本了吗？打开你的网站cpu瞬间飙80.

### ISSUE THREAD

**Issue by penndev** [HeZhaoJiang/hezhaojiang.github.io#1]
系统是 MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports) 11.6
浏览器是 Google Chrome

正在更新 Google Chrome
版本 93.0.4577.82（正式版本） (x86_64)

打开网站cpu就跑满。 太恐怖了。

**Comment by penndev** [comment]
MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports) 11.6

**Comment by penndev** [comment]
系统是 MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports) 11.6 
浏览器是 Google Chrome

正在更新 Google Chrome
版本 93.0.4577.82（正式版本） (x86_64)

打开网站cpu就跑满。   太恐怖了。

**Comment by hezhaojiang** [comment]
没有 Mac 没法测试，win11 i7 9700 我试了下，CPU涨了10%左右，可能是我放JS脚本放太多了，可能需要删除点没用的动画 @penndev

**Comment by hezhaojiang** [comment]
@penndev 删除了页面波浪动画和页面的Live2D人物模型，CPU占用降下来了
